# Generated by Django 6.0.3 on 2026-04-01 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('pages', '0005_alter_page_page_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsubmission',
            name='section_id',
        ),
        migrations.AddField(
            model_name='leadsubmission',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.section', verbose_name='Секция формы'),
        ),
    ]
