# Generated by Django 6.0.3 on 2026-03-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
