# Generated by Django 6.0.3 on 2026-03-15 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-адрес')),
                ('page_type', models.CharField(choices=[('default', 'Обычная страница'), ('contacts', 'Контакты'), ('news_list', 'Новости'), ('gallery', 'Галерея')], default='default', max_length=20, verbose_name='Тип страницы')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('seo_desc', models.TextField(blank=True, verbose_name='SEO описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в меню')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hero', 'Обложка (Hero)'), ('text', 'Текстовый блок'), ('counters', 'Счётчики / Достижения'), ('cards', 'Карточки с преимуществами'), ('team', 'Команда'), ('steps', 'Этапы / Нумерованный список'), ('table', 'Таблица'), ('chart_pie', 'Круговая диаграмма'), ('form', 'Форма обратной связи'), ('faq', 'Вопросы и ответы'), ('testimonials', 'Отзывы')], max_length=20, verbose_name='Тип секции')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видима')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ['order'],
            },
        ),
    ]
