# Generated by Django 6.0.3 on 2026-03-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('hero', 'Обложка (Hero)'), ('text', 'Текстовый блок'), ('counters', 'Счётчики / Достижения'), ('cards', 'Карточки с преимуществами'), ('team', 'Команда'), ('steps', 'Этапы / Нумерованный список'), ('table', 'Таблица'), ('chart_pie', 'Круговая диаграмма'), ('form', 'Форма обратной связи'), ('faq', 'Вопросы и ответы'), ('testimonials', 'Отзывы'), ('contacts', 'Контактная информация')], max_length=20, verbose_name='Тип секции'),
        ),
    ]
