# Generated by Django 6.0.3 on 2026-03-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_chart_pie_to_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='draft_data',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Черновик'),
        ),
    ]
