# Generated by Django 6.0.3 on 2026-03-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_section_draft_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('default', 'Обычная страница'), ('news_list', 'Новости'), ('gallery', 'Галерея')], default='default', max_length=20, verbose_name='Тип страницы'),
        ),
    ]
