"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Загрузка переменных из .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'unfold', # тема Admin
    'unfold.contrib.filters', # расширенные фильтры
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Приложения проекта
    'pages',
    'navigation',
    'appearance',
    'accounts',
    'news',
    'gallery',
    'leads',
    'charts',
    'media_library',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'navigation.context_processors.navigation',
                'appearance.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Папка для загружаемых файлов
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media_files'


from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "ModuleCMS",
    "SITE_HEADER": "ModuleCMS",
    "SITE_SUBHEADER": "Панель управления",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Сайт"),
                "items": [
                    {
                        "title": _("Страницы"),
                        "icon": "article",
                        "link": "/admin/pages/page/",
                    },
                    {
                        "title": _("Навигация"),
                        "icon": "menu",
                        "link": "/admin/navigation/menuitem/",
                    },
                ],
            },
            {
                "title": _("Контент"),
                "items": [
                    {
                        "title": _("Новости"),
                        "icon": "newspaper",
                        "link": "/admin/news/newspost/",
                    },
                    {
                        "title": _("Галерея"),
                        "icon": "photo_library",
                        "link": "/admin/gallery/galleryitem/",
                    },
                    {
                        "title": _("Медиафайлы"),
                        "icon": "perm_media",
                        "link": "/admin/media_library/mediafile/",
                    },
                ],
            },
            {
                "title": _("Продажи"),
                "items": [
                    {
                        "title": _("Заявки"),
                        "icon": "inbox",
                        "link": "/admin/leads/leadsubmission/",
                    },
                ],
            },
            {
                "title": _("Настройки"),
                "items": [
                    {
                        "title": _("Оформление"),
                        "icon": "palette",
                        "link": "/admin/appearance/sitetheme/",
                    },
                    {
                        "title": _("Пользователи"),
                        "icon": "people",
                        "link": "/admin/auth/user/",
                    },
                ],
            },
        ],
    },
}