# Generated by Django 6.0.3 on 2026-03-15 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Пользовательская')),
                ('primary', models.CharField(default='#2563eb', max_length=7, verbose_name='Primary (кнопки, акценты)')),
                ('background', models.CharField(default='#ffffff', max_length=7, verbose_name='Background (фон страницы)')),
                ('surface', models.CharField(default='#f8fafc', max_length=7, verbose_name='Surface (фон карточек)')),
                ('accent', models.CharField(default='#1d4ed8', max_length=7, verbose_name='Accent (hover-эффекты)')),
                ('text', models.CharField(default='#1e293b', max_length=7, verbose_name='Text (основной текст)')),
            ],
            options={
                'verbose_name': 'Тема оформления',
                'verbose_name_plural': 'Темы оформления',
            },
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Загруженный шрифт')),
                ('google_font_name', models.CharField(blank=True, max_length=100, verbose_name='Название в Google Fonts')),
                ('fallback', models.CharField(default='sans-serif', max_length=100, verbose_name='Запасной шрифт')),
                ('custom_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.mediafile', verbose_name='Файл шрифта (.woff2)')),
            ],
            options={
                'verbose_name': 'Шрифт',
                'verbose_name_plural': 'Шрифты',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Мой сайт', max_length=200, verbose_name='Название сайта')),
                ('home_slug', models.SlugField(default='glavnaya', verbose_name='Slug главной страницы')),
                ('active_font', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appearance.font', verbose_name='Активный шрифт')),
                ('active_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appearance.theme', verbose_name='Активная тема')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
