# Generated by Django 6.0.3 on 2026-03-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_map_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на карту (embed)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
    ]
