# Generated by Django 6.0.3 on 2026-03-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0002_sitesettings_contact_address_and_more'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='home_slug',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon_settings', to='media_library.mediafile', verbose_name='Фавикон (.ico или .png)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_settings', to='media_library.mediafile', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_mode',
            field=models.CharField(choices=[('logo_and_name', 'Логотип и название'), ('logo_only', 'Только логотип'), ('name_only', 'Только название'), ('hidden', 'Скрыть')], default='name_only', max_length=20, verbose_name='Навигация: логотип и название'),
        ),
    ]
