# Generated by Django 6.0.3 on 2026-03-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0003_remove_sitesettings_home_slug_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_map_url',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Отображается в футере и на странице «Контакты»', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Отображается в футере и на странице «Контакты»', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_hours',
            field=models.CharField(blank=True, help_text='Отображается только на странице «Контакты»', max_length=200, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Отображается в футере и на странице «Контакты»', max_length=100, verbose_name='Телефон'),
        ),
    ]
