# Generated by Django 6.0.3 on 2026-03-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_remove_sitesettings_contact_map_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
    ]
