# Generated by Django 6.0.3 on 2026-03-15 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('document', 'Документ')], default='image', max_length=20, verbose_name='Тип')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
